from Adafruit_IO import MQTTClient
AIO_USERNAME = "iotg06"
AIO_KEY = "aio_pZLL43LGAxfNGAXoiLtYy6LCOd0X"

FEED_DOOR = "DOOR"
FEED_FAN = "FAN"
FEED_HUMIDITY = "HUMIDITY"
FEED_LIGHT = "LIGHT"
FEED_REFRESHER = "REFRESHER"
FEED_TEMP = "TEMP"
FEED_WARNING = "WARING"

client = MQTTClient(AIO_USERNAME, AIO_KEY)
